wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/new", views.new, name="new"),
    path("wiki/", views.entry, name="entry"),
    path("wiki/search", views.search, name="search"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/edit/<str:title>", views.edit, name="edit")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render ,redirect
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import util
from django.http import HttpResponse
import markdown2
from django.views import defaults


class SearchForm(forms.Form):
    search_query = forms.CharField(label="")

class NewForm(forms.Form):
    new_title = forms.CharField(label="Enter the title of the new page", widget=forms.TextInput(attrs={'placeholder': 'Title', 'style': 'width: 300px;', 'class': 'form-control'}))
    new_body = forms.CharField(label="Enter the markdown body of the new page", widget=forms.Textarea(attrs={'placeholder': 'Body', 'class': 'form-control'}))

class EditForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly', 'class': 'form-control'}))
    body = forms.CharField(label="Edit the markdown body of the page", widget=forms.Textarea(attrs={'class': 'form-control'}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form": SearchForm()
    })


def entry(request, title="entry"):
    if util.get_entrt_try_all(title):
        return render(request, "encyclopedia/entry.html", {
            "entry": markdown2.markdown(util.get_entrt_try_all(title)),
            "title" : title,
            "form": SearchForm(),
            "entries": util.list_entries(),
            "entry_flag": True
        })
    else:
        return render(request, "encyclopedia/entry.html", {
            "title" : title,
            "form": SearchForm(),
            "entries": util.list_entries(),
            "entry_flag": False
        })


def new(request):
    if request.method == "POST":
        form = NewForm(request.POST)
        if form.is_valid():
            new_title = form.cleaned_data["new_title"]
            new_body = form.cleaned_data["new_body"]
            if util.get_entrt_try_all(new_title):
                return render(request, "encyclopedia/new.html", {
                    "form": SearchForm(),
                    "entries": util.list_entries(),
                    "new_form": form,
                    "error_msg": "ERROR : This title already exists"
                })
            else:
                util.save_entry(new_title, new_body)
                return redirect("encyclopedia:entry", title=new_title)
        else:
            return render(request, "encyclopedia/new.html", {
                "form": SearchForm(),
                "entries": util.list_entries(),
                "new_form": form,
            })
    else:
        return render(request, "encyclopedia/new.html", {
        "form": SearchForm(),
        "entries": util.list_entries(),
        "new_form": NewForm()
    })


def search(request):
    form = SearchForm(request.POST)
    if form.is_valid():
        title = form.cleaned_data["search_query"]
        if util.get_entrt_try_all(title):
            return HttpResponseRedirect(reverse("encyclopedia:entry", args=[title]))
        else:
            list_all_entries = util.list_entries()
            list_valid_entries = list(filter(lambda x: title.lower() in x.lower(), list_all_entries))
            return render(request, "encyclopedia/search.html", {
            "title": title,
            "valid_entries": list_valid_entries,
            "entries": util.list_entries(),
            "form": SearchForm()
            })
    else:
        return render(request,"encyclopedia/search.html", {
            "entries": util.list_entries(),
            "form": form
        })



def edit(request, title):
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            body = form.cleaned_data["body"]
            title = form.cleaned_data["title"]
            util.save_entry(title, body)
            return redirect("encyclopedia:entry", title=title)
        else:
            return render(request, "encyclopedia/edit.html", {
                "form": SearchForm(),
                "entries": util.list_entries(),
                "edit_form": form,
            })
    else:
        if util.get_entrt_try_all(title):
            body = util.get_entrt_try_all(title)
            return render(request, "encyclopedia/edit.html", {
                "title" : title,
                "form": SearchForm(),
                "entries": util.list_entries(),
                "edit_form": EditForm(initial = {"title": title, "body": body})
            })
        else:
            return defaults.page_not_found(request, "")

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit {{ title }}
{% endblock %}



{% block body %}
    <form action="{% url 'encyclopedia:edit' title %}" method="post"> 
        {% csrf_token %}
        {{ edit_form }}
        <input type="submit" value="Save" id="save_page">
    </form>
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{% if entry_flag %}
    {{ title|title }}
{% else %}
    {{ title|title }} not found!
{% endif %}

{% endblock %}

{% block body %}

{% if entry_flag %}
    {{ entry |safe}}
{% else %}
    Requested page was not found
{% endif %}

<form action="{% url 'encyclopedia:edit' title %}">
    <input type="submit" value="Edit" id="edit_page">
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post"> 
                    {% csrf_token %}
                    {{ form }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:entry' entries|random %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Create New Page
{% endblock %}



{% block body %}
    <form action="{% url 'encyclopedia:new' %}" method="post"> 
        {% csrf_token %}
        {{ new_form }}
        <input type="submit" value="Save" id="save_page">
    </form>
    {% if error_msg %}
        {{ error_msg }}
    {% endif %}
    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search results
{% endblock %}

{% block body %}

    {% if valid_entries|length == 0 %}
        <h1>No Search Results for <b>{{ title }} </b> </h1>
    {% else %}
        <h1>Search Results for <b>{{ title }} </b> </h1>
    {% endif %}
    <ul>
        {% for entry in valid_entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}